### ISSUE TITLE
Title character spacing

### ISSUE THREAD

**Issue by ianrobertlambert** [GetLuko/streamline#42]
### Problem
The negative % character spacing (-1%) on `Title SM`, `Title MD` and `Title LG` is causing strange rendering on iOS and Android devices. This was clearly evident on the CardSummary and may display awkwardly on other devices.

### Proposed Solution
To address this issue, we propose removing the character spacing. This should prevent further rendering issues and ensure consistent display across devices.

**Comment by hcourthias** [comment]
I will take care of the changes :)

**Comment by ianrobertlambert** [comment]
Thanks @hcourthias :)
