### ISSUE TITLE
Update to appearance naming for: CardCallout, CardTip and Tag

### ISSUE THREAD

**Issue by ianrobertlambert** [GetLuko/streamline#43]
# Problem
Currently, different components in our mobile design system display `Primary` and `Neutral` appearances differently. This inconsistency is a result of the components being created before aligning on `Primary`, `Secondary`, `Neutral`, `Warning`, `Danger`, `Success` appearance conventions.

# Proposed Solution
To address this inconsistency, we propose updating the following components to align with the new appearance conventions:

- **CardCallout**
- **CardTip**
- **Tag**

For each component, we suggest that `Primary` should become what is currently the `Secondary` appearance, while `Secondary` should become what is currently the `Primary` appearance. Additionally, `Secondary` should be renamed to `Neutral` to maintain consistency with the naming conventions. For example:

### CardCallout
![image](https://user-images.githubusercontent.com/34472045/232494294-1e0335bc-5d50-4bfe-843a-ea3be8348114.png)

### CardTip
![image](https://user-images.githubusercontent.com/34472045/232494527-51e7d249-59a8-448b-badc-4e2e5df8074c.png)

### Tag
![image](https://user-images.githubusercontent.com/34472045/232495545-d25d8c5b-659c-4133-8bd6-4abcae790a69.png)

# Questions
- Is it possible to add `Dark` and `Light` appearance to Tags? If yes, I can create a separate ticket for this if necessary, as it was not raised in the original feedback and the issue is now closed.
![image](https://user-images.githubusercontent.com/34472045/232495958-bd39766e-5390-4147-8b9b-1384f56c46dc.png)

**Comment by ianrobertlambert** [comment]
FYI @kimak @judastheo

**Comment by judastheo** [comment]
Good for me! I will take care of the update and will add the dark and light tag at the same time

**Comment by ianrobertlambert** [comment]
> Good for me! I will take care of the update and will add the dark and light tag at the same time

Thanks @judastheo ! 👌
